# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang++-4.0
      env: COMPILER=clang++-4.0
before_install:
  # - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq

install:
  # - sudo apt-get install -y cmake

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j4
