# Ubuntu 18.04 (Bionic Beaver) support
sudo: required
dist: bionic

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang++-8
      env: COMPILER=clang++-8
before_install:
  # - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq

install:
  # - sudo apt-get install -y cmake

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j4
